[US22] Implement retweets and answers
Leonert/FP3SocialNetwork pull request #40
Opened 2023-05-09 13:31 UTC by CoffeeScriptHero

2023-05-09 18:05 UTC, himik80 submitted a review, later dismissed

2023-05-10 09:29 UTC, Leonert requested changes
qq

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/controller/PostController.java
> +    Integer originalPostId = postDto.getOriginalPostId();
excessive object creation

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/controller/PostController.java
> +    String header = request.getHeader(AUTHORIZATION_HEADER);
excessive

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/controller/PostController.java
> +    User user = userService.getReferenceById(postDto.getUser().getId());
searching for the primary key depends only on the user id and post id, there is no need to request whole entities. Map DTO`s to empty users or implement query to DB which will add/delete records by id`s not entities

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/controller/PostController.java
> +    if (bookmarkService.existsByUserAndPost(user, post)) {
This logic should be in service. Call for method 'switch' only in the controller, for example. And reduce excessive object creation.

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/controller/PostController.java
> +  private Post convertToPost(PostDto.Request.Created postDto, User user, Integer originalPostId)
don`t pass originalpostid here. Just check if postdto`s original post exists, if not, throw an exception, if yes, map it, There is no need to save it if the request data is incorrect.

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/controller/PostController.java
> +      Post originalPost = postService.findById(postDto.getOriginalPost().getId()).get();
throw an exception if not found

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/controller/PostController.java
> +      postDto.getOriginalPost().setLikesNumber(likeService.countPostLikes(originalPost));
Let frontend take the number of likes from the original post if it`s a retweet. There is no need for the additional counter for them in the retweet.

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/dto/LikeDto.java
get rid of this file

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/service/BookmarkService.java
> +  public void save(User user, Post post) {
do it with constructor not mapping

2023-05-10 09:29 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/service/LikeService.java
> +  public void save(User user, Post post) {
the same constructor thing

2023-05-10 14:58 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/dto/LikeDto.java
> +  ;
?

2023-05-10 14:58 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/dto/LikeDto.java
> +    ;
?

2023-05-10 14:58 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/dto/LikeDto.java
> +    ;
?

2023-05-10 14:59 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/service/PostService.java
> +    return postRepository.findAll(PageRequest.of(page, postsNumber, Sort.by("createdDate")))
Can we use List.of()?

2023-05-10 15:01 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/service/PostService.java
> +    return postRepository.findAll(PageRequest.of(page, postsNumber, Sort.by("createdDate")))
use List.of() instead of or for what?

2023-05-10 15:03 UTC, Leonert commented on social-network-api/src/main/java/com/socialnetwork/api/dto/LikeDto.java
> +    ;
https://habr.com/ru/articles/513072/

2023-05-10 15:03 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/service/PostService.java
> +    return postRepository.findAll(PageRequest.of(page, postsNumber, Sort.by("createdDate")))
instead of stream().toList()

2023-05-10 15:06 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/dto/LikeDto.java
> +    ;
🤦‍♂️

2023-05-11 09:26 UTC, Leonert approved these changes

2023-05-11 10:48 UTC, TarasSkorohod approved these changes

2023-05-11 10:49 UTC, merged