F5.7
Leonert/FP3SocialNetwork pull request #42
Opened 2023-05-12 15:03 UTC by himik80

2023-05-12 15:54 UTC, bymooon commented on social-network-ui/src/routes/router.js
Render element SettingsPage in different route.

2023-05-12 15:59 UTC, bymooon requested changes
Render element SettingsPage in different route.

2023-05-13 07:27 UTC, miegami approved these changes

2023-05-14 09:14 UTC, miegami commented
Please, resolve merge conflicts.

2023-05-14 09:15 UTC, miegami commented on social-network-ui/src/components/PasswordChenge/PasswordChange.jsx
> +import VisibilityIcon from '@mui/icons-material/Visibility';
Rename the folder for this file.

2023-05-19 20:07 UTC, TarasSkorohod approved these changes

2023-05-20 06:39 UTC, bymooon approved these changes

2023-05-20 06:40 UTC, merged