B7.1
Leonert/FP3SocialNetwork pull request #44
Opened 2023-05-12 18:30 UTC by TarasSkorohod

2023-05-14 09:15 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/controller/MessagesController.java
> +    // Журналирование списка messageDtos
Please, don't leave any comments or do it on English,

2023-05-14 09:16 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/dto/MessageDto.java
> +  private boolean read;
Could you rename it to the isRead?

2023-05-14 09:16 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/dto/MessageDto.java
> +  private int id;
Maybe it would be better to use long here?

2023-05-14 09:17 UTC, miegami commented on social-network-api/src/main/java/com/socialnetwork/api/models/base/Message.java
> +  private String username;
Why do we need this field? We already have the sender and the recipient.

2023-05-14 09:19 UTC, miegami commented on social-network-api/src/main/resources/test.http
> +}
Please, remove this file.

2023-05-14 09:20 UTC, miegami commented on social-network-ui/src/pages/Messages/Messages.jsx
> +  const getAllMessages = async () => {
What about using WebSockets to receive real-time messages?

2023-05-14 09:21 UTC, miegami commented on social-network-ui/src/pages/Messages/MessagesStyles.jsx
> +    // color: theme.palette.common.white,
Please, remove commented styles.

2023-05-14 09:21 UTC, miegami commented on social-network-ui/src/pages/Messages/MessagesStyles.jsx
> +      // backgroundColor: theme.palette.background.paper,
Please, remove commented styles.

2023-05-14 09:21 UTC, miegami commented on social-network-ui/src/services/api/chatApi.js
> +            return null;
It would be better to have a general error handler with an error page or error modal.

2023-05-15 09:37 UTC, miegami commented
Need to resolve merge conflicts.

2023-05-28 10:17 UTC, miegami approved these changes

2023-05-28 10:17 UTC, miegami requested changes
Fix build

2023-06-22 09:31 UTC, CoffeeScriptHero approved these changes

2023-06-22 15:21 UTC, miegami approved these changes

2023-06-22 15:22 UTC, merged